# Install Terraform extension to use this task from:
# https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks&ssr=false#overview
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.14.0'
  inputs:
    terraformVersion: 0.14.0
# Terraform versions: https://releases.hashicorp.com/terraform/
